### ISSUE TITLE
使用第三方登录后  除了头像其他资料都无法修改

### ISSUE THREAD

**Issue by Yakumo-Yukari** [notbucai/blog3.0#25]
用户名
职位
请输入职位
公司
请输入公司
个人介绍
请输入个人介绍
个人主页

这些都没办法修改的啊 是不允许修改吗？

**Comment by notbucai** [comment]
可以修改，之前优化加载的时候有点bug，晚点会修复

**Comment by notbucai** [comment]
fix https://github.com/notbucai/blog3.0/commit/6ae1723e7a82e68de9e7b76ac3f8a28b1c6a4960
